services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vidsync_api
    ports:
      - "7123:7123" # HTTPS
      - "5123:5123" # HTTP
    environment:
      - ASPNETCORE_URLS=https://+:7123;http://+:5123
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ConnectionStrings__Redis=redis:6379
      - JWT__Key=${JWT__Key}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
    volumes:
      - ./src/Core/VidSync.API/localhost+3.p12:/app/localhost+3.p12:ro
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: vidsync_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - vidsync_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: vidsync_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: vidsync_cloudflared
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - api

volumes:
  vidsync_data:
    driver: local
