version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vidsync_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: vidsync_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db_data:
    driver: local
