name: 📝 New Error&Bug
description: Create a new task for the project.
title: "[TASK TITLE]: "
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: What is the purpose of this task? What needs to be done? Please provide all necessary context and details here.
      placeholder: "In this task, an API endpoint will be created to allow users to reset their passwords..."
    validations:
      required: true
